name: "Deno Check"

on:
  push:
    branches: ["main"]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup Deno"
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: "Run Lint"
        run: deno task lint

      - name: "Run Format"
        run: deno task format
